---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	intent_node(intent_node)
	blueprint_node(blueprint_node)
	section_planner_node(section_planner_node)
	folder_struct_node(folder_struct_node)
	section_builder_node(section_builder_node)
	page_generator_node(page_generator_node)
	__end__(<p>__end__</p>)
	__start__ --> intent_node;
	blueprint_node --> page_generator_node;
	blueprint_node --> section_planner_node;
	intent_node --> blueprint_node;
	page_generator_node -. &nbsp;END&nbsp; .-> __end__;
	section_builder_node -. &nbsp;END&nbsp; .-> __end__;
	section_planner_node --> section_builder_node;
	page_generator_node -.-> page_generator_node;
	section_builder_node -.-> section_builder_node;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
