import JSZip from "jszip";
import { useCallback } from "react";

interface FileData {
  path: string;
  content: string;
}

interface DownloadButtonProps {
  files: FileData[];
}

// ─── Scaffold ─────────────────────────────────────────────────────────────────

const PACKAGE_JSON = `{
  "name": "generated-site",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint"
  },
  "dependencies": {
    "framer-motion": "^12.35.0",
    "lucide-react": "^0.577.0",
    "next": "16.1.6",
    "react": "19.2.3",
    "react-dom": "19.2.3"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^9",
    "eslint-config-next": "16.1.6",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}`;

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts",
    "**/*.mts"
  ],
  "exclude": ["node_modules"]
}`;

const POSTCSS_CONFIG = `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;

const NEXT_CONFIG = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: [
    "192.168.137.1",
    "localhost"
  ],
};

export default nextConfig;
`;

const ESLINT_CONFIG = `import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
`;

const GITIGNORE = `# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files
.env*

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`;

const APP_GLOBALS_CSS = `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
}
`;

const APP_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Generated Site",
  description: "Generated by Idelyze AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}>
        {children}
      </body>
    </html>
  );
}
`;

const SCAFFOLD: Record<string, string> = {
  "package.json": PACKAGE_JSON,
  "tsconfig.json": TSCONFIG,
  "postcss.config.mjs": POSTCSS_CONFIG,
  "next.config.ts": NEXT_CONFIG,
  "eslint.config.mjs": ESLINT_CONFIG,
  ".gitignore": GITIGNORE,
  "next-env.d.ts": NEXT_ENV_DTS,
  "app/globals.css": APP_GLOBALS_CSS,
  "app/layout.tsx": APP_LAYOUT,
};

// ─── Path mapper ──────────────────────────────────────────────────────────────
// Sections/* → app/sections/*
// Anything else root-level or unknown → app/*

function mapPath(rawPath: string): string {
  const parts = rawPath.split("/");
  const top = parts[0];
  const rest = parts.slice(1).join("/");

  const MAP: Record<string, string> = {
    Sections: "app/sections",
    sections: "app/sections",
    Components: "app/components",
    components: "app/components",
    Hooks: "app/hooks",
    hooks: "app/hooks",
    Lib: "lib",
    lib: "lib",
    Utils: "lib/utils",
    utils: "lib/utils",
    Types: "types",
    types: "types",
    Public: "public",
    public: "public",
  };

  if (parts.length === 1) {
    // root-level file like page.tsx → app/page.tsx
    return `app/${rawPath}`;
  }

  if (MAP[top]) {
    return `${MAP[top]}/${rest}`;
  }

  // unknown folder → put under app/
  return `app/${rawPath}`;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function DownloadButton({ files }: DownloadButtonProps) {
  const isEmpty = files.length === 0;

  const downloadFiles = useCallback(async () => {
    if (isEmpty) return;

    const zip = new JSZip();
    const root = zip.folder("generated-site")!;

    // 1. Scaffold files
    Object.entries(SCAFFOLD).forEach(([path, content]) => {
      root.file(path, content);
    });

    // 3. Generated files — mapped to correct Next.js paths
    files.forEach((f) => {
      root.file(mapPath(f.path), f.content);
    });

    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "generated-site.zip";
    a.click();
    URL.revokeObjectURL(url);
  }, [files, isEmpty]);

  return (
    <button
      type="button"
      onClick={downloadFiles}
      disabled={isEmpty}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "6px 14px",
        fontSize: 12,
        fontFamily: "'IBM Plex Mono', monospace",
        fontWeight: 500,
        borderRadius: 2,
        border: `1px solid ${isEmpty ? "var(--border-main)" : "var(--green)"}`,
        cursor: isEmpty ? "not-allowed" : "pointer",
        background: "transparent",
        color: isEmpty ? "var(--text3)" : "var(--green)",
        transition: "all 0.15s",
        whiteSpace: "nowrap",
      }}
    >
      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      {isEmpty ? "no files" : `export next.js (${files.length})`}
    </button>
  );
}
